language: node_js
node_js:
- '4'
- stable

services: mongodb

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: XzcoQZjCTra14Tt3YHdSXmPm6b+Nm1kBVs3JBCFI74ZnDuDUhacao+NdgjyKBcnfqQb5ofdSO5c2cbaCMDqYs+bXMqiHhBsr2lK93KnlRT5mmlAe/PFeJgv5OR+SKC4jUDqluUKpnbHQkVb1XPpUvklGjzvHv8g+xFDFYwuxYjhTLhgISTuoDtNwszUGKunIoYttwRRI2XH18TA6KJ0FDtMj+nNGBDEQ3MvY1eQMuHYfAx1RsGnZKkWpgt5TdImTF1NDq0VJ9hIfj21mSq4rpkPDBGPnEqOflmjo73KeYWRgqxAmEyO4PVLAeXUk1UVE1ATX36WUeBXM1YUDRR4+Vti3acR4N53ZJ9fdwtw5TxZu2Ep4Cg/8MqjNFoiEsq0l3okd2tMpHeC+GpDyYWp53yt+mAsYpVpGJA/15b6yaSBl+9BbmjPHByEBE5Cv025acUwD+Gr3Isj9nggp4JcsEpJrnmWCmBMk+Igfod1+luam4uR8GCU0RlIZTwdEzjg3YLNgxsrC6z+VYbaRgu5NcQe10bTP3umDBkcSLXVNnrGIw/St550PXOVXrU6u7Dq+3WXpQKJUXu+a9hrKSbxRNxD6OMZRBo2Ve2ffcMd+ZVEwlS4m7IvQkGl4SUgwYeUqj2oTB6nNDJFoFWVEMG5NRbC01XzPMD8Q7jjVg+lirrs=
  on:
    tags: true
    repo: trailsjs/trailpack-mongoose
    node: stable
